{
 "title": "Дисциплина труда",
 "time": { "from": "2021-08-30T00:00:00.000Z", "to": "2023-07-30T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Employee",
    "query": "SELECT full_name FROM employee;"
   }
  ]
 },
 "panels": [
  {
   "title": "График сравнения времени работы между днями недели",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nDAYNAME(a.work_date) AS day_of_week,\nAVG(TIMESTAMPDIFF(MINUTE, a.arrival_time, a.departure_time)) AS avg_work_duration_minutes\nFROM attendance a\nJOIN employee e ON e.id = a.employee_id\nWHERE e.full_name IN($Employee ) AND a.arrival_time IS NOT NULL AND a.departure_time IS NOT NULL\nGROUP BY day_of_week"
    }
   ]
  },
  {
   "title": "График распределения времени прихода",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT HOUR(arrival_time) AS hour, COUNT(*) AS count\nFROM attendance\nJOIN employee e ON e.id = employee_id\nWHERE e.full_name IN ($Employee)  AND arrival_time IS NOT NULL\nGROUP BY hour"
    }
   ]
  },
  {
   "title": "График сравнения рабочего времени между сотрудниками",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "employee_attendance",
     "rawSql": "SELECT e.full_name, SUM(TIMESTAMPDIFF(MINUTE, a.arrival_time, a.departure_time)) AS total_minutes\nFROM employee e\nLEFT JOIN attendance a ON e.id = a.employee_id\nWHERE e.full_name IN($Employee )\nGROUP BY e.full_name\nORDER BY total_minutes DESC\n\n"
    }
   ]
  },
  {
   "title": "График общего времени работы в определенный день",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "employee_attendance",
     "rawSql": "SELECT work_date, SUM(TIMESTAMPDIFF(MINUTE, arrival_time, departure_time)) AS total_minutes\nFROM attendance a\nJOIN employee e ON e.id = a.employee_id\nWHERE e.full_name IN($Employee) AND arrival_time is NOT NULL\nGROUP BY work_date\n"
    }
   ]
  }
 ]
}